# This file is part of django-flask-sessions.
# https://github.com/pnegahdar/django-flask-sessions

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Parham Negahdar <pnegahdar@gmail.com>

language: python

python:
    - "2.7"

services:
  - redis-server

script:
    # run tests
    - pip install inenv
    - make test

after_success:
  - coveralls
